/lslidar_driver_node:
  ros__parameters: 
    frame_id: base_scan                    
    group_ip: 224.1.1.2
    add_multicast: false 
    device_ip: 192.168.1.200
    device_ip_difop: 192.168.1.102
    msop_port: 2368
    difop_port: 2369
    lidar_name: N10
    # angle_disable_min: -180.0
    # angle_disable_max: -90.0
    angle_disable_min: -178.0 
    angle_disable_max: -92.0
    # angle_disable_min: 0.0 
    # angle_disable_max: 0.0
    min_range: 0.1
    max_range: 100.0
    use_gps_ts: false
    scan_topic: /scan
    interface_selection: serial
    serial_port_: /dev/ttyLiDAR
    high_reflection: false
    compensation: false
    pubScan: true
    pubPointCloud2: false
    pointcloud_topic: /lslidar_point_cloud

